#' Run training set simulation
#' @keywords internal
#' @author Ghislain Durif
#' @details
#'  -h, --header arg        Header file (default: headerRF.txt)
#'  -r, --reftable arg      Reftable file (default: reftableRF.bin)
#'  -b, --statobs arg       Statobs file (default: statobsRF.txt)
#'  -o, --output arg        Prefix output (modelchoice_out or estimparam_out by
#'                                         default)
#'  -n, --nref arg          Number of samples, 0 means all (default: 0)
#'  -m, --minnodesize arg   Minimal node size. 0 means 1 for classification or
#'  5 for regression (default: 0)
#'  -t, --ntree arg         Number of trees (default: 500)
#'  -j, --threads arg       Number of threads, 0 means all (default: 0)
#'  -s, --seed arg          Seed, generated by default (default: 0)
#'  -c, --noisecolumns arg  Number of noise columns (default: 5)
#'  --nolinear          Disable LDA for model choice or PLS for parameter
#'  estimation
#'  --plsmaxvar arg     Percentage of maximum explained Y-variance for
#'  retaining pls axis (default: 0.9)
#'  --chosenscen arg    Chosen scenario (mandatory for parameter
#'                                       estimation)
#'  --noob arg          number of oob testing samples (mandatory for
#'                                                     parameter estimation)
#'  --parameter arg     name of the parameter of interest (mandatory for
#'                                                         parameter estimation)
#'  -g, --groups arg        Groups of models
abcranger_run <- function(proj_dir, mode, n_ref, 
                          min_node_size, n_tree, noise_columns, no_linear, 
                          pls_max_var, chosen_scenario, noob, parameter, 
                          groups = NULL) {
    # # debugging
    # print("abcranger args")
    # print(match.call())
    
    # executable
    abcranger_bin <- find_bin("abcranger")
    # check project dir
    if(!dir.exists(proj_dir)) {
        stop("Input directory does not exist")
    }
    
    # go to project directory
    wd <- getwd()
    on.exit(setwd(wd))
    setwd(proj_dir)
    
    # run cmd
    cmd <- str_c(
        abcranger_bin, 
        "-n", n_ref,
        "-m", min_node_size,
        "-t", n_tree,
        "-j", getOption("diyabcGUI")$ncore,
        "-c", noise_columns,
        sep = " "
    )
    if(no_linear) {
        cmd <- str_c(
            cmd,
            "--no_linear",
            sep = " "
        )
    } else {
        cmd <- str_c(
            cmd,
            "--plsmaxvar", pls_max_var,
            sep = " "
        )
    }
    if(mode == "param_estim") {
        cmd <- str_c(
            cmd,
            "--chosenscen", chosen_scenario,
            "--noob", noob,
            "--parameter", parameter,
            sep = " "
        )
    }
    if(!is.null(groups)) {
        cmd <- str_c(
            cmd,
            "-g", groups,
            sep = " "
        )
    }
    # logging
    cmd <- str_c(
        cmd,
        ">", file.path(proj_dir, str_c("abcranger_", mode, "_call.log")),
        sep = " "
    )
    logging("abcranger cmd", cmd)
    check <- system(cmd)
    logging("abcranger run", check)
    if(check != 0) {
        warning("Issue with seed initialization")
    }
    # output
    return(lst(check))
}
