#' Run training set simulation
#' @keywords internal
#' @author Ghislain Durif
#' @details
#'  -h, --header arg        Header file (default: headerRF.txt)
#'  -r, --reftable arg      Reftable file (default: reftableRF.bin)
#'  -b, --statobs arg       Statobs file (default: statobsRF.txt)
#'  -o, --output arg        Prefix output (modelchoice_out or estimparam_out by
#'                                         default)
#'  -n, --nref arg          Number of samples, 0 means all (default: 0)
#'  -m, --minnodesize arg   Minimal node size. 0 means 1 for classification or
#'  5 for regression (default: 0)
#'  -t, --ntree arg         Number of trees (default: 500)
#'  -j, --threads arg       Number of threads, 0 means all (default: 0)
#'  -s, --seed arg          Seed, generated by default (default: 0)
#'  -c, --noisecolumns arg  Number of noise columns (default: 5)
#'  --nolinear          Disable LDA for model choice or PLS for parameter
#'  estimation
#'  --plsmaxvar arg     Percentage of maximum explained Y-variance for
#'  retaining pls axis (default: 0.9)
#'  --chosenscen arg    Chosen scenario (mandatory for parameter
#'                                       estimation)
#'  --noob arg          number of oob testing samples (mandatory for
#'                                                     parameter estimation)
#'  --parameter arg     name of the parameter of interest (mandatory for
#'                                                         parameter estimation)
#'  -g, --groups arg        Groups of models
abcranger_run <- function(proj_dir, mode, n_ref, 
                          min_node_size, n_tree, noise_columns, no_linear, 
                          pls_max_var, chosen_scenario, noob, parameter, 
                          groups = NULL) {
    # # debugging
    # print("abcranger args")
    # print(match.call())
    
    # executable
    abcranger_bin <- find_bin("abcranger")
    
    # check project dir
    if(!dir.exists(proj_dir)) {
        stop("Input directory does not exist")
    }
    
    # check for required files
    required_files <- c("headerRF.txt", "statobsRF.txt", "reftableRF.bin")
    if(!all(required_files %in% list.files(proj_dir))) {
        stop("missing required input file(s)")
    }
    
    ### run
    logging("abcranger run")
    arguments <- c(
        "-n", n_ref,
        "-m", min_node_size,
        "-t", n_tree,
        "-j", getOption("diyabcGUI")$ncore,
        "-c", noise_columns
    )
    if(no_linear) {
        arguments <- c(arguments, "--no_linear")
    } else {
        arguments <- c(arguments, "--plsmaxvar", pls_max_var)
    }
    if(mode == "param_estim") {
        arguments <- c(
            arguments,
            "--chosenscen", chosen_scenario,
            "--noob", noob,
            "--parameter", parameter
        )
    }
    if(!is.null(groups)) {
        arguments <- c(arguments, "-g", groups)
    }
    
    run_proc <- processx::process$new(
        command = abcranger_bin, 
        args = arguments,
        stdout = file.path(proj_dir, str_c("abcranger_", mode, "_call.log")), 
        stderr = file.path(proj_dir, str_c("abcranger_", mode, "_call.log")),
        echo_cmd = TRUE,
        wd = proj_dir
    )
    
    ## output process
    return(run_proc)
}

#' Clean up after abcranger
#' @keywords internal
#' @author Ghislain Durif
cleanup_abcranger_run <- function(project_dir) {
    ## file list
    files <- file.path(
        project_dir,
        c("abcranger_param_estim_call.log", 
          "abcranger_mod_choice_call.log")
    )
    # remove files
    lapply(files, function(filename) {
        if(file.exists(filename)) {
            fs::file_delete(filename)
        }
    })
}
